/**
 * API surface model for the Playwright suite.
 *
 * Every endpoint of the amabay API is described once, here, as a plain object.
 * Tests reference these objects instead of hard-coding method/path strings, so
 * a route change is a one-line edit in this file.
 *
 * `generateBody()` produces a request body for any endpoint that requires one
 * (POST create, PATCH update). Endpoints with `requiresBody: false` yield
 * `undefined`.
 */

export type HttpMethod = 'GET' | 'POST' | 'PATCH' | 'DELETE';

/** Which body shape an endpoint expects, if any. */
export type BodyKind = 'create' | 'update';

export interface Endpoint {
  /** Stable key, also used in test titles. */
  name: string;
  method: HttpMethod;
  /** True when the endpoint expects a JSON request body. */
  requiresBody: boolean;
  /** The body shape to generate; only meaningful when requiresBody is true. */
  bodyKind?: BodyKind;
  /**
   * Builds the request path. Collection endpoints ignore the argument;
   * item endpoints interpolate the id.
   */
  path: (id?: number | string) => string;
  /** Human-readable summary for documentation / test output. */
  description: string;
}

// ---------------------------------------------------------------------------
// One object per endpoint.
// ---------------------------------------------------------------------------
export const endpoints = {
  health: {
    name: 'health',
    method: 'GET',
    requiresBody: false,
    path: () => '/health',
    description: 'Liveness/health probe',
  },
  listItems: {
    name: 'listItems',
    method: 'GET',
    requiresBody: false,
    path: () => '/api/items',
    description: 'List/search items with pagination',
  },
  getItem: {
    name: 'getItem',
    method: 'GET',
    requiresBody: false,
    path: (id) => `/api/items/${id}`,
    description: 'Fetch a single item by id',
  },
  createItem: {
    name: 'createItem',
    method: 'POST',
    requiresBody: true,
    bodyKind: 'create',
    path: () => '/api/items',
    description: 'Create an item',
  },
  updateItem: {
    name: 'updateItem',
    method: 'PATCH',
    requiresBody: true,
    bodyKind: 'update',
    path: (id) => `/api/items/${id}`,
    description: 'Partial update of an item',
  },
  deleteItem: {
    name: 'deleteItem',
    method: 'DELETE',
    requiresBody: false,
    path: (id) => `/api/items/${id}`,
    description: 'Delete an item',
  },
} satisfies Record<string, Endpoint>;

export type EndpointName = keyof typeof endpoints;

// ---------------------------------------------------------------------------
// Request body generation.
// ---------------------------------------------------------------------------

/** The full item payload accepted by the create endpoint. */
export interface ItemBody {
  title: string;
  price: number;
  quantity: number;
  description?: string;
  image?: string;
}

// Monotonic counter so titles/markers are unique within a run, even if two
// bodies are generated in the same millisecond.
let seq = 0;

/** A run-unique token, handy for isolating a test's rows via `?q=`. */
export function uniqueMarker(prefix = 'e2e'): string {
  seq += 1;
  return `${prefix}-${Date.now()}-${seq}`;
}

/** Round to 2 decimals to keep prices realistic for an ecommerce catalog. */
function money(): number {
  return Number((Math.random() * 100 + 1).toFixed(2));
}

/**
 * Generate a request body for the given endpoint.
 *
 * - `create` endpoints get a complete, valid item (all required fields plus
 *   optional description/image).
 * - `update` endpoints get a valid partial body containing a single field, so
 *   it satisfies the "at least one field" rule without touching everything.
 * - Endpoints that take no body return `undefined`.
 *
 * `overrides` are shallow-merged last, so a test can pin or invalidate any
 * field (e.g. `{ price: -1 }` to exercise the validation path).
 */
export function generateBody(
  endpoint: Endpoint,
  overrides: Partial<ItemBody> = {}
): ItemBody | Partial<ItemBody> | undefined {
  if (!endpoint.requiresBody) return undefined;

  if (endpoint.bodyKind === 'create') {
    const marker = uniqueMarker();
    const body: ItemBody = {
      title: `Item ${marker}`,
      price: money(),
      quantity: Math.floor(Math.random() * 50) + 1,
      description: `Autogenerated item ${marker}`,
      image: 'https://example.com/item.jpg',
    };
    return { ...body, ...overrides };
  }

  // bodyKind === 'update' — a valid, non-empty partial update.
  const partial: Partial<ItemBody> = { price: money() };
  return { ...partial, ...overrides };
}
